// vue/src/App.vue
<script setup lang="ts">
import Counter from './components/Counter.vue'
</script>

<template>
  <div>
    <a href="https://vite.dev" target="_blank">
      <img src="/vite.svg" class="logo" alt="Vite logo" />
    </a>
    <a href="https://vuejs.org/" target="_blank">
      <img src="./assets/vue.svg" class="logo vue" alt="Vue logo" />
    </a>
    <a href="https://livesession.dev" target="_blank">
      <img src="./assets/ls.png" className="logo livesession" alt="LiveSession logo"/>
    </a>
  </div>
  <h1>
    Vite + Vue + LiveSession
  </h1>

  <Counter />

  <p class="read-the-docs">Click on the Vite, Vue or LiveSession logos to learn more</p>

</template>

<style scoped>
.logo {
  height: 6em;
  padding: 1.5em;
  will-change: filter;
  transition: filter 300ms;
}
.logo:hover {
  filter: drop-shadow(0 0 2em #646cffaa);
}
.logo.vue:hover {
  filter: drop-shadow(0 0 2em #42b883aa);
}
</style>

// react/src/App.tsx
import {useEffect, useState} from 'react'

import ls from "@livesession/browser"

import reactLogo from './assets/react.svg'
import lsLogo from './assets/ls.png'
import viteLogo from '/vite.svg'
import './App.css'

function App() {
    const [count, setCount] = useState(0)

    useEffect(() => {
        ls.track("Counter", {
            value: count
        })
    }, [count])

    return (
        <>
            <div>
                <a href="https://vite.dev" target="_blank">
                    <img src={viteLogo} className="logo" alt="Vite logo"/>
                </a>
                <a href="https://react.dev" target="_blank">
                    <img src={reactLogo} className="logo react" alt="React logo"/>
                </a>
                <a href="https://livesession.io" target="_blank">
                    <img src={lsLogo} className="logo livesession" alt="LiveSession logo"/>
                </a>
            </div>
            <h1>Vite + React + LiveSession</h1>
            <div className="card">
                <button onClick={() => setCount((count) => count + 1)}>
                    count is {count}
                </button>
            </div>
            <p className="read-the-docs">
                Click on the Vite, React or LiveSession logos to learn more
            </p>
        </>
    )
}

export default App
