// vue/src/App.vue
<script setup lang="ts">
import Counter from './components/Counter.vue'
</script>

<template>
  <div>
    <a href="https://vite.dev" target="_blank">
      <img src="/vite.svg" class="logo" alt="Vite logo" />
    </a>
    <a href="https://vuejs.org/" target="_blank">
      <img src="./assets/vue.svg" class="logo vue" alt="Vue logo" />
    </a>
    <a href="https://livesession.dev" target="_blank">
      <img src="./assets/ls.png" className="logo livesession" alt="LiveSession logo"/>
    </a>
  </div>
  <h1>
    Vite + Vue + LiveSession
  </h1>

  <Counter />

  <p class="read-the-docs">Click on the Vite, Vue or LiveSession logos to learn more</p>

</template>

<style scoped>
.logo {
  height: 6em;
  padding: 1.5em;
  will-change: filter;
  transition: filter 300ms;
}
.logo:hover {
  filter: drop-shadow(0 0 2em #646cffaa);
}
.logo.vue:hover {
  filter: drop-shadow(0 0 2em #42b883aa);
}
</style>

// next/src/app/page.tsx
import Image from "next/image";
import styles from "./page.module.css";
import Counter from "./components/Counter";

export default function Home() {
  return (
    <div className={styles.page}>
      <main className={styles.main}>
        <div className={styles.logos}>
          <a href="https://nextjs.org" target="_blank" rel="noopener noreferrer">
            <Image
              className={styles.logo}
              src="/next.svg"
              alt="Next.js logo"
              width={180}
              height={38}
              priority
            />
          </a>
          <span className={styles.plus}>+</span>
          <a href="https://livesession.dev" target="_blank" rel="noopener noreferrer">
            <Image
              className={styles.logo}
              src="/ls.png"
              alt="LiveSession logo"
              width={96}
              height={96}
              priority
            />
          </a>
        </div>

        <Counter />

        <ol>
          <li>
            Get started check out <code>src/app/livesession.tsx</code>.
          </li>
        </ol>

        <div className={styles.ctas}>
          Click on the Next.js, LiveSession logos to learn more
        </div>
      </main>
    </div>
  );
}
